#+title: My Goals for this Website
#+options: num:nil html-postamble:nil

* Introduction
I acquired this domain a few months ago, but I haven't really done anything serious with it.
The cool domain hack was something I couldn't resist, and I ended up acquiring it.
My hopes for this website wasn't for this to be some polished, professional, page that is marketable to
the everyman (that hope was already thrown away with the super unprofessional domain name).
Not only do I want this website to document the cool stuff I've worked on, but I want this to
be something cool enough to "wow" my friends.

* Projects
One of the important things this website will contain are documents of
projects that I've worked on, preferrably in ~org-mode~.
This will be the hard evidence that I put in some thought into what I made.
I've already testpiloted this concept through my notes on Peter Shirley's guide to
[[https://raytracing.github.io/books/RayTracingInOneWeekend.html][Ray Tracing in One Weekend]].
So if I wanted to revisit something I did, or wanted to explain a concept I learned
in more detail, I can reference these notes.

* Toys
I hope that from the things I learn from my projects, I can extend these concepts even
further to create interactive widgets that anyone can play with. These can also be
things I wanted to make on the whim, like a pdf combiner (because I want a convenient way
to merge PDFs without uploading anything to the server-side).

** Ideas
- I learned about cubic splines recently, so it would be interesting to create a drawing program
  that samples points from the cursor and interpolate lines from those points.
- Ever since I saw the program that rendered a rotating ascii doughnut, I wanted to
  attempt something similar and show it off on my website. Maybe I can use what I learned
  from ray-tracing.
- For now, most of the plain-text pages are done in pure org-mode. If I have anything that needs
  something a bit more complex, I usually write it in HTML. However, it would be nice to style
  the HTML exports that come out of org-mode
- As already mentioned, it would be nice to have my own client-side PDF merger. That way,
  I am sure my documents aren't being uploaded to any server.

